### ISSUE TITLE
Cannot Connect to MSZ-AP42VGD with MAC-568

### ISSUE THREAD

**Issue by steven-ellis** [scottyphillips/echonetlite_homeassistant#114]
I have 3 Mitsubishi units and can only get two working

- MSZ-AP25VGD + MAC-568  - WORKS
- PEAD-M71JAA + MAC-568  - WORKS
- MSZ-AP42VGD + MAC-568 - Can't connect
I've tried resetting the units and turning EchoNet off/on via the WiFi app.

All the units are accessible via WIFI on the Mitsubishi App.

**Comment by nao-pon** [comment]
First, please reconfirm that the IP address is correct. And could you please set the debug level to debug in the developer tools service like below, then run the config flow and provide the logs?

```yaml
service: logger.set_level
data:
  custom_components.echonetlite: debug
```
