### ISSUE TITLE
Not sure how/where to set temperature in an automation

### ISSUE THREAD

**Issue by Jinsterrrr** [scottyphillips/echonetlite_homeassistant#170]
Hi Scott. Thank you so much for your efforts in making this plug-in. It works very well with my Mitsubishi ducted units.

My question, if anyone can please help, is that there doesn't appear to be a way to set a target temperature in HA.

1. In terms of trigger, what is the difference between "measured temperature changed" vs "Measured value of room temperature temperature changes"? Those are the exact wording in the trigger section.
2. In terms of the effect action, it allows Action "Change HVAC mode" to hvac_mode "cool" - but there appears to be no way to set a cool to what target temperature

Or is it just a case of "keeping the temperature at the trigger temperature"?

Ideally, I would like it so that once the temperature reaches 28 deg Celcius, I can then set it to cool to a target of 20 deg, for example. This allows a buffer zone so that the AC isn't always running whenever it gets above 20 deg. I would tolerate living slightly warm until an unbearable temperature, that's the idea here.

**Comment by scottyphillips** [comment]
Try something like this. I use this in winter time.

```
alias: HVAC - Turn off heater if temperature exceeds 18 degrees after 10 and before 6
trigger:
  - platform: numeric_state
    above: "18"
    entity_id: sensor.temperature_humidity_sensor_366b_temperature
  - platform: numeric_state
    entity_id: sensor.temperature_humidity_sensor_1d53_temperature
    above: 19
    enabled: false
  - platform: numeric_state
    entity_id: sensor.temperature_humidity_sensor_438b_temperature
    above: 19
condition:
  - after: "22:00:00"
    before: "06:00:00"
    condition: time
action:
  - service: climate.turn_off
    data: {}
    target:
      entity_id: climate.mitsubishi_ducted
initial_state: true
mode: single

alias: >-
  HVAC - Turn on heater if temperature gets below 16 degrees after 10 and before
  5
trigger:
  - below: "16"
    platform: numeric_state
    entity_id: sensor.temperature_humidity_sensor_366b_temperature
  - platform: numeric_state
    entity_id: sensor.temperature_humidity_sensor_438b_temperature
    below: "15.5"
condition:
  - after: "22:00:00"
    before: "05:00:00"
    condition: time
action:
  - service: climate.turn_on
    target:
      entity_id: climate.mitsubishi_ducted
    data: {}
initial_state: true
mode: single
```
